### ISSUE TITLE
Transição de imagens durante pagamento

### ISSUE THREAD

**Issue by victorsampaio** [ibugsolution/AppMotoSeguros#11]
Melhorias nas informações demonstradas na máquina durante o processo de pagamento.
Ex.:
Inserir o cartão;
Transação do pagamento e etc.
Essas animações podem ser adaptadas para melhorar o entendimento do usuário durante o ciclo de pagamento.

**Comment by tioago** [comment]
Foi realizado uma alteração de forma que os textos apresentados na máquina já melhorem a visualização do que precisa ser realizado no sistema.

**Comment by tioago** [comment]
Entrei online com o Daniel e já resolvemos os problemas, mostrando os dialogs com as respectivas imagens.
