### ISSUE TITLE
Alterar a cor do CardView na lista de Oferta

### ISSUE THREAD

**Issue by victorsampaio** [ibugsolution/AppMotoSeguros#12]
Na lista de oferta, o CardView de cada item deve apresentar uma cor referente a sua Família.
O json recebido da API trás a informação de atributo referente a um arquivo 'rgb'.

É possível estar enviando um hexadecimal se for necessário.

**Comment by ibugsolution** [comment]
O modelo atual já disponibiliza da modificação de cores de fonte e fundo do cartão com a api transacionando e executando no cardview, contudo foi solicitado a inserção de uma imagem.

**Comment by ibugsolution** [comment]
As necessidades iniciais da tarefa foram concluídas troca de cor de fonte e background do cardview, os testes se demonstram positivos, motivo pelo a tarefa está concluída.
Caso ocorra novas modificações uma nova tarefa será aberta.
