### ISSUE TITLE
Aplicação do valores parcelados no pagamento

### ISSUE THREAD

**Issue by ibugsolution** [ibugsolution/AppMotoSeguros#14]
Na tela activity_transaction o componente installmentsSpinner demonstram os possíveis valores de pagamento em parcelas. O calculo é feito por meio de uma api com acesso ao servidor, contudo o valor a ser enviado para a Stone como pagamento é o obtido no campo valorDaConta e não dando a opção de selecionar o valor a ser pago parcelado.

**Comment by tioago** [comment]
Corrigido o problema e já subido para a master, aguardando testes

**Comment by ibugsolution** [comment]
Testes realizados com êxito.
