### ISSUE TITLE
Modelo de placa MERCOSUL (Tela Veículo);

### ISSUE THREAD

**Issue by victorsampaio** [ibugsolution/AppMotoSeguros#9]
Alterar o formato de entrada de dados da placa de veículos. Atualmente sendo dois campos o primeiro com três letras e o segundo com quatro números.
O novo modelo é três letras e a sequencia de um número, um letra e dois números. Ex; A placa modelo antigo DYU1001 ao passar para modelo novo será DYU1A01.

**Comment by tioago** [comment]
Corrigido o problema de validação da placa do mercosul.
